GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRnJhbnoiLCJpYXQiOjE3MTk0ODk0OTYsImV4cCI6MTcxOTQ4OTUyNn0.HyoIzYS0qRBcQSwmeVgLX6rvjHiR__O7vZ3SV2-rJN8

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRnJhbnoiLCJpYXQiOjE3MTk0ODk0OTYsImV4cCI6MTcxOTQ4OTUyNn0.HyoIzYS0qRBcQSwmeVgLX6rvjHiR__O7vZ3SV2-rJN8"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "Franz"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRnJhbnoiLCJpYXQiOjE3MTk0ODk0OTYsImV4cCI6MTcxOTQ4OTUyNn0.HyoIzYS0qRBcQSwmeVgLX6rvjHiR__O7vZ3SV2-rJN8"
}